services:
  web:
    build: .
    container_name: web-46
    command: >
      sh -c "
      python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "127.0.0.1:25046:8000"
    volumes:
      - ./config:/app
